<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" 
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.metaeffekt.kontinuum.runtime</groupId>
        <artifactId>ae-kontinuum-runtime</artifactId>
        <version>HEAD-SNAPSHOT</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <artifactId>ae-kontinuum-runtime-container</artifactId>
    <packaging>pom</packaging>

    <dependencies>
        <dependency>
            <groupId>org.metaeffekt.kontinuum.runtime</groupId>
            <artifactId>ae-kontinuum-runtime-execution</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>

    <profiles>
        <profile>
            <id>build-container</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.codehaus.mojo</groupId>
                        <artifactId>exec-maven-plugin</artifactId>
                        <version>3.6.3</version>
                        <executions>
                            <execution>
                                <id>run-container-build-script</id>
                                <phase>install</phase>
                                <goals>
                                    <goal>exec</goal>
                                </goals>
                                <configuration>
                                    <executable>${project.basedir}/build.sh</executable>
                                    <workingDirectory>${project.basedir}</workingDirectory>

                                    <arguments>
                                        <argument>${ae.core.version}</argument>
                                        <argument>${ae.artifact.analysis.version}</argument>
                                        <argument>${ae.portfolio.manager.version}</argument>
                                        <argument>${ae.kontinuum.branch}</argument>
                                        <argument>${docker.image.tag}</argument>
                                        <argument>${docker.username}</argument>
                                        <argument>${docker.access.token}</argument>
                                        <argument>${docker.registry}</argument>
                                    </arguments>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
