package org.metaeffekt.kontinuum.runtime.generator.local;

import lombok.Getter;
import lombok.extern.slf4j.Slf4j;
import org.apache.commons.lang3.StringUtils;
import org.metaeffekt.kontinuum.runtime.generator.shared.Pipeline;
import org.metaeffekt.kontinuum.runtime.models.local.LocalConfiguration;
import org.metaeffekt.kontinuum.runtime.models.shared.PipelineConfiguration;
import org.metaeffekt.kontinuum.runtime.models.shared.PipelineConfiguration.ProjectProperties.Asset;
import org.metaeffekt.kontinuum.runtime.models.shared.ProcessorDefinitions.MavenProcessor;
import org.metaeffekt.kontinuum.runtime.models.shared.ProcessorDefinitions.Processor;
import org.metaeffekt.kontinuum.runtime.models.shared.ProcessorDefinitions.ProcessorParameter;
import org.metaeffekt.kontinuum.runtime.models.shared.ProcessorDefinitions.StandaloneProcessor;

import java.util.List;
import java.util.Map;

/**
 * Generates a local-execution shell script from the configured pipeline.
 *
 * <p>The output is a sequence of chained {@code mvn -f <processor-pom> <goal>} invocations,
 * one per processor, ordered by stage. The script is intended to be executed on the
 * developer's machine (macOS, Linux). Windows compatibility is left open via the
 * {@link LocalConfiguration.ExecutionEnvironment} enum for future implementation.
 */
@Slf4j
public class LocalPipeline {

    /**
     * -- GETTER --
     *  Convenience accessor for the resolved processor map. Useful for tests.
     */
    @Getter
    private final Map<Asset, List<Processor>> assetProcessorsMap;

    private final StringBuilder scriptDocument = new StringBuilder();

    private final LocalConfiguration localConfiguration;

    public LocalPipeline(PipelineConfiguration pipelineConfiguration, LocalConfiguration localConfiguration) {
        this.localConfiguration = localConfiguration;
        Pipeline pipeline = new Pipeline(pipelineConfiguration, localConfiguration);
        this.assetProcessorsMap = pipeline.generatePipeline();
    }

    public String generatePipeline() {
        generateHeader();
        generateProcessorSteps();
        return scriptDocument.toString();
    }

    private void generateHeader() {
        scriptDocument.append("#!/usr/bin/env bash").append(System.lineSeparator());
        scriptDocument.append("# Auto-generated by ae-kontinuum-runtime-execution:generate-local-pipeline").append(System.lineSeparator());
        scriptDocument.append("# Do not edit manually; regenerate from the kontinuum configuration.").append(System.lineSeparator());
        scriptDocument.append("set -e").append(System.lineSeparator());
        scriptDocument.append(System.lineSeparator());
    }

    private void generateProcessorSteps() {
        for (Map.Entry<Asset, List<Processor>> entry : assetProcessorsMap.entrySet()) {
            String assetName = entry.getKey().toString();
            for (Processor processor : entry.getValue()) {
                ProcessorStep step = new ProcessorStep(processor, assetName);

                scriptDocument.append("# --- ").append(step.processor.getStage()).append(": ")
                        .append(step.processor.getId()).append(" (").append(step.assetName).append(") ----")
                        .append(System.lineSeparator());

                if (step.processor instanceof MavenProcessor mavenProcessor) {
                    scriptDocument.append(generateMavenScriptBlock(mavenProcessor));
                } else if (step.processor instanceof StandaloneProcessor standaloneProcessor) {
                    scriptDocument.append(standaloneProcessor.getScript()).append(System.lineSeparator());
                }
            }
        }
    }

    private String generateMavenScriptBlock(MavenProcessor processor) {
        StringBuilder script = new StringBuilder();

        if (StringUtils.isNotBlank(processor.getPreScript())) {
            script.append(processor.getPreScript()).append(System.lineSeparator());
        }

        script.append("mvn -f ")
                .append(localConfiguration.getKontinuumProcessorsDirNormalized())
                .append(processor.getPomLocation()).append(" ")
                .append(processor.getGoal()).append(" \\").append(System.lineSeparator());

        List<ProcessorParameter> nonBlankParams = processor.getParameters().stream()
                .filter(p -> StringUtils.isNotBlank(p.getValue()))
                .toList();

        for (int i = 0; i < nonBlankParams.size(); i++) {
            ProcessorParameter param = nonBlankParams.get(i);
            script.append("    -D").append(param.getKey()).append("='").append(param.getValue()).append("'");
            if (i < nonBlankParams.size() - 1) {
                script.append(" \\");
            }
            script.append(System.lineSeparator());
        }

        if (StringUtils.isNotBlank(processor.getPostScript())) {
            script.append(processor.getPostScript()).append(System.lineSeparator());
        }

        return script.toString();
    }

    private record ProcessorStep(Processor processor, String assetName) {}

}