package org.metaeffekt.kontinuum.runtime.generator.local;

import lombok.Getter;
import lombok.extern.slf4j.Slf4j;
import org.apache.commons.lang3.StringUtils;
import org.metaeffekt.kontinuum.runtime.generator.shared.Pipeline;
import org.metaeffekt.kontinuum.runtime.generator.shared.PipelineExecution;
import org.metaeffekt.kontinuum.runtime.models.local.LocalConfiguration;
import org.metaeffekt.kontinuum.runtime.models.shared.ExecutionContext;
import org.metaeffekt.kontinuum.runtime.models.shared.PipelineConfiguration;
import org.metaeffekt.kontinuum.runtime.models.shared.PipelineConfiguration.ProjectProperties.Asset;
import org.metaeffekt.kontinuum.runtime.models.shared.ProcessorDefinitions.MavenProcessor;
import org.metaeffekt.kontinuum.runtime.models.shared.ProcessorDefinitions.Processor;
import org.metaeffekt.kontinuum.runtime.models.shared.ProcessorDefinitions.ProcessorParameter;
import org.metaeffekt.kontinuum.runtime.models.shared.ProcessorDefinitions.StandaloneProcessor;

import java.util.List;

/**
 * Generates a local-execution shell script from the configured pipeline.
 *
 * <p>The output is a serial sequence of chained {@code mvn -f <processor-pom> <goal>} invocations,
 * ordered by processor dependencies, then stage, then registration order. The script is intended to
 * be executed on the developer's machine (macOS, Linux). Windows compatibility is left open via the
 * {@link LocalConfiguration.ExecutionEnvironment} enum for future implementation.
 */
@Slf4j
public class LocalPipeline {

    /**
     * -- GETTER --
     *  Convenience accessor for the resolved execution. Useful for tests.
     */
    @Getter
    private final PipelineExecution execution;

    private final StringBuilder scriptDocument = new StringBuilder();

    private final LocalConfiguration localConfiguration;

    public LocalPipeline(PipelineConfiguration pipelineConfiguration, LocalConfiguration localConfiguration) {
        this(new Pipeline(pipelineConfiguration, localConfiguration).generatePipeline(), localConfiguration);
    }

    LocalPipeline(PipelineExecution execution, LocalConfiguration localConfiguration) {
        this.localConfiguration = localConfiguration;
        this.execution = execution;
    }

    public String generatePipeline() {
        generateHeader();
        generateProcessorSteps();
        return scriptDocument.toString();
    }

    private void generateHeader() {
        scriptDocument.append("#!/usr/bin/env bash").append(System.lineSeparator());
        scriptDocument.append("# Auto-generated by ae-kontinuum-runtime-execution:generate-local-pipeline").append(System.lineSeparator());
        scriptDocument.append("# Do not edit manually; regenerate from the kontinuum configuration.").append(System.lineSeparator());
        scriptDocument.append("set -e").append(System.lineSeparator());
        scriptDocument.append(System.lineSeparator());
    }

    private void generateProcessorSteps() {
        for (Processor processor : execution.getOrderedProcessors()) {
            ExecutionContext context = execution.getContext(processor);
            scriptDocument.append("# --- ").append(processor.getStage().name()).append(": ")
                    .append(processor.getId()).append(" (").append(context.getName()).append(") ----")
                    .append(System.lineSeparator());

            if (processor instanceof MavenProcessor mavenProcessor) {
                scriptDocument.append(generateMavenScriptBlock(mavenProcessor));
            } else if (processor instanceof StandaloneProcessor standaloneProcessor) {
                scriptDocument.append(generateStandaloneScriptBlock(standaloneProcessor));
            }
        }
    }

    private String generateMavenScriptBlock(MavenProcessor processor) {
        StringBuilder script = new StringBuilder();

        if (StringUtils.isNotBlank(processor.getPreScript())) {
            script.append(processor.getPreScript()).append(System.lineSeparator());
        }

        script.append("mvn ");
        if (StringUtils.isNotBlank(localConfiguration.MAVEN_CLI_OPTS)) {
            script.append(localConfiguration.MAVEN_CLI_OPTS).append(" ");
        }
        if (StringUtils.isNotBlank(localConfiguration.LOCAL_MAVEN_REPO)) {
            script.append("-Dmaven.repo.local=").append(localConfiguration.LOCAL_MAVEN_REPO).append(" ");
        }
        script.append("-f ")
                .append(localConfiguration.getKontinuumProcessorsDirNormalized())
                .append(processor.getPomLocation())
                .append(" process-resources").append(" \\").append(System.lineSeparator());

        List<ProcessorParameter> nonBlankParams = processor.getParameters().stream()
                .filter(p -> StringUtils.isNotBlank(p.getValue()))
                .toList();

        for (int i = 0; i < nonBlankParams.size(); i++) {
            ProcessorParameter param = nonBlankParams.get(i);
            script.append("    -D").append(param.getKey()).append("='").append(param.getValue()).append("'");
            if (i < nonBlankParams.size() - 1) {
                script.append(" \\");
            }
            script.append(System.lineSeparator());
        }

        if (StringUtils.isNotBlank(processor.getPostScript())) {
            script.append(processor.getPostScript()).append(System.lineSeparator());
        }

        return script.toString();
    }

    private String generateStandaloneScriptBlock(StandaloneProcessor processor) {
        StringBuilder script = new StringBuilder();
        script.append("sh ")
                .append(localConfiguration.getKontinuumProcessorsDirNormalized())
                .append(processor.getScriptLocation());

        for (ProcessorParameter parameter : processor.getParameters()) {
            if (parameter != null && StringUtils.isNotBlank(parameter.getValue())) {
                script.append(" ").append(parameter.getValue());
            }
        }
        return script.append(System.lineSeparator()).toString();
    }
}
